// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-fetch';
import type { AnalyticsServiceRecordWeightData, AnalyticsServiceRecordWeightResponse, AnalyticsServiceRecordWeightError, AnalyticsServiceGetWeightHistoryData, AnalyticsServiceGetWeightHistoryResponse, AnalyticsServiceGetWeightHistoryError, AnalyticsServiceSubmitFeedbackData, AnalyticsServiceSubmitFeedbackResponse, AnalyticsServiceSubmitFeedbackError, AnalyticsServiceGetUserProgressReportData, AnalyticsServiceGetUserProgressReportResponse, AnalyticsServiceGetUserProgressReportError, AnalyticsServiceGetTestimonialsData, AnalyticsServiceGetTestimonialsResponse, GeneticServiceCreateGeneticTestData, GeneticServiceCreateGeneticTestResponse, GeneticServiceCreateGeneticTestError, GeneticServiceGetSampleReportData, GeneticServiceGetSampleReportResponse, GeneticServiceGetUserGeneticTestData, GeneticServiceGetUserGeneticTestResponse, GeneticServiceGetUserGeneticTestError, GeneticServiceGetAllSupplementsData, GeneticServiceGetAllSupplementsResponse, GeneticServiceGetUserRecommendationsData, GeneticServiceGetUserRecommendationsResponse, GeneticServiceGetUserRecommendationsError, SubscriptionServiceCreateSubscriptionData, SubscriptionServiceCreateSubscriptionResponse, SubscriptionServiceCreateSubscriptionError, SubscriptionServiceGetUserSubscriptionData, SubscriptionServiceGetUserSubscriptionResponse, SubscriptionServiceGetUserSubscriptionError, SubscriptionServiceUpdateSubscriptionStatusData, SubscriptionServiceUpdateSubscriptionStatusResponse, SubscriptionServiceUpdateSubscriptionStatusError, SubscriptionServiceCreateDeliveryData, SubscriptionServiceCreateDeliveryResponse, SubscriptionServiceCreateDeliveryError, SubscriptionServiceGetUserDeliveriesData, SubscriptionServiceGetUserDeliveriesResponse, SubscriptionServiceGetUserDeliveriesError, SubscriptionServiceGetPricingInfoData, SubscriptionServiceGetPricingInfoResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

/**
 * Analytics Service Record Weight
 * Record user&#39;s weight measurement.
 */
export const analyticsServiceRecordWeight = <ThrowOnError extends boolean = false>(options: Options<AnalyticsServiceRecordWeightData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<AnalyticsServiceRecordWeightResponse, AnalyticsServiceRecordWeightError, ThrowOnError>({
        url: '/api/analytics_service/record_weight',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Analytics Service Get Weight History
 * Get user&#39;s weight history for the specified number of days.
 */
export const analyticsServiceGetWeightHistory = <ThrowOnError extends boolean = false>(options: Options<AnalyticsServiceGetWeightHistoryData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<AnalyticsServiceGetWeightHistoryResponse, AnalyticsServiceGetWeightHistoryError, ThrowOnError>({
        url: '/api/analytics_service/get_weight_history',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Analytics Service Submit Feedback
 * Submit user feedback for a supplement.
 */
export const analyticsServiceSubmitFeedback = <ThrowOnError extends boolean = false>(options: Options<AnalyticsServiceSubmitFeedbackData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<AnalyticsServiceSubmitFeedbackResponse, AnalyticsServiceSubmitFeedbackError, ThrowOnError>({
        url: '/api/analytics_service/submit_feedback',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Analytics Service Get User Progress Report
 * Generate a progress report for the user.
 */
export const analyticsServiceGetUserProgressReport = <ThrowOnError extends boolean = false>(options: Options<AnalyticsServiceGetUserProgressReportData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<AnalyticsServiceGetUserProgressReportResponse, AnalyticsServiceGetUserProgressReportError, ThrowOnError>({
        url: '/api/analytics_service/get_user_progress_report',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Analytics Service Get Testimonials
 * Get customer testimonials for the landing page.
 */
export const analyticsServiceGetTestimonials = <ThrowOnError extends boolean = false>(options?: Options<AnalyticsServiceGetTestimonialsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<AnalyticsServiceGetTestimonialsResponse, unknown, ThrowOnError>({
        url: '/api/analytics_service/get_testimonials',
        ...options
    });
};

/**
 * Genetic Service Create Genetic Test
 * Create a new genetic test request and user profile.
 */
export const geneticServiceCreateGeneticTest = <ThrowOnError extends boolean = false>(options: Options<GeneticServiceCreateGeneticTestData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<GeneticServiceCreateGeneticTestResponse, GeneticServiceCreateGeneticTestError, ThrowOnError>({
        url: '/api/genetic_service/create_genetic_test',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Genetic Service Get Sample Report
 * Get a sample genetic analysis report for demonstration.
 */
export const geneticServiceGetSampleReport = <ThrowOnError extends boolean = false>(options?: Options<GeneticServiceGetSampleReportData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<GeneticServiceGetSampleReportResponse, unknown, ThrowOnError>({
        url: '/api/genetic_service/get_sample_report',
        ...options
    });
};

/**
 * Genetic Service Get User Genetic Test
 * Get user&#39;s genetic test status and results.
 */
export const geneticServiceGetUserGeneticTest = <ThrowOnError extends boolean = false>(options: Options<GeneticServiceGetUserGeneticTestData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<GeneticServiceGetUserGeneticTestResponse, GeneticServiceGetUserGeneticTestError, ThrowOnError>({
        url: '/api/genetic_service/get_user_genetic_test',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Genetic Service Get All Supplements
 * Get all available supplements.
 */
export const geneticServiceGetAllSupplements = <ThrowOnError extends boolean = false>(options?: Options<GeneticServiceGetAllSupplementsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<GeneticServiceGetAllSupplementsResponse, unknown, ThrowOnError>({
        url: '/api/genetic_service/get_all_supplements',
        ...options
    });
};

/**
 * Genetic Service Get User Recommendations
 * Get user&#39;s personalized supplement recommendations.
 */
export const geneticServiceGetUserRecommendations = <ThrowOnError extends boolean = false>(options: Options<GeneticServiceGetUserRecommendationsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<GeneticServiceGetUserRecommendationsResponse, GeneticServiceGetUserRecommendationsError, ThrowOnError>({
        url: '/api/genetic_service/get_user_recommendations',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Subscription Service Create Subscription
 * Create a new subscription for a user.
 */
export const subscriptionServiceCreateSubscription = <ThrowOnError extends boolean = false>(options: Options<SubscriptionServiceCreateSubscriptionData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SubscriptionServiceCreateSubscriptionResponse, SubscriptionServiceCreateSubscriptionError, ThrowOnError>({
        url: '/api/subscription_service/create_subscription',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Subscription Service Get User Subscription
 * Get user&#39;s current subscription status.
 */
export const subscriptionServiceGetUserSubscription = <ThrowOnError extends boolean = false>(options: Options<SubscriptionServiceGetUserSubscriptionData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SubscriptionServiceGetUserSubscriptionResponse, SubscriptionServiceGetUserSubscriptionError, ThrowOnError>({
        url: '/api/subscription_service/get_user_subscription',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Subscription Service Update Subscription Status
 * Update subscription status (활성, 일시정지, 해지).
 */
export const subscriptionServiceUpdateSubscriptionStatus = <ThrowOnError extends boolean = false>(options: Options<SubscriptionServiceUpdateSubscriptionStatusData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SubscriptionServiceUpdateSubscriptionStatusResponse, SubscriptionServiceUpdateSubscriptionStatusError, ThrowOnError>({
        url: '/api/subscription_service/update_subscription_status',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Subscription Service Create Delivery
 * Create a new delivery for a subscription.
 */
export const subscriptionServiceCreateDelivery = <ThrowOnError extends boolean = false>(options: Options<SubscriptionServiceCreateDeliveryData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SubscriptionServiceCreateDeliveryResponse, SubscriptionServiceCreateDeliveryError, ThrowOnError>({
        url: '/api/subscription_service/create_delivery',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Subscription Service Get User Deliveries
 * Get all deliveries for a user&#39;s subscriptions.
 */
export const subscriptionServiceGetUserDeliveries = <ThrowOnError extends boolean = false>(options: Options<SubscriptionServiceGetUserDeliveriesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SubscriptionServiceGetUserDeliveriesResponse, SubscriptionServiceGetUserDeliveriesError, ThrowOnError>({
        url: '/api/subscription_service/get_user_deliveries',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Subscription Service Get Pricing Info
 * Get current pricing information.
 */
export const subscriptionServiceGetPricingInfo = <ThrowOnError extends boolean = false>(options?: Options<SubscriptionServiceGetPricingInfoData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SubscriptionServiceGetPricingInfoResponse, unknown, ThrowOnError>({
        url: '/api/subscription_service/get_pricing_info',
        ...options
    });
};