// This file is auto-generated by @hey-api/openapi-ts

export type BodyAnalyticsServiceGetUserProgressReport = {
    user_id: string;
};

export type BodyAnalyticsServiceGetWeightHistory = {
    user_id: string;
    days: number;
};

export type BodyAnalyticsServiceRecordWeight = {
    user_id: string;
    weight: number;
    memo?: string | null;
};

export type BodyAnalyticsServiceSubmitFeedback = {
    user_id: string;
    supplement_id: string;
    effectiveness_score: number;
    has_side_effects: boolean;
    detailed_review?: string | null;
};

export type BodyGeneticServiceCreateGeneticTest = {
    user_id: string;
    full_name: string;
    phone: string;
    email: string;
    address: {
        [key: string]: unknown;
    };
};

export type BodyGeneticServiceGetUserGeneticTest = {
    user_id: string;
};

export type BodyGeneticServiceGetUserRecommendations = {
    user_id: string;
};

export type BodySubscriptionServiceCreateDelivery = {
    subscription_id: string;
    delivery_address: {
        [key: string]: unknown;
    };
    product_list: Array<{
        [key: string]: unknown;
    }>;
};

export type BodySubscriptionServiceCreateSubscription = {
    user_id: string;
    payment_info: {
        [key: string]: unknown;
    };
};

export type BodySubscriptionServiceGetUserDeliveries = {
    user_id: string;
};

export type BodySubscriptionServiceGetUserSubscription = {
    user_id: string;
};

export type BodySubscriptionServiceUpdateSubscriptionStatus = {
    subscription_id: string;
    new_status: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type AnalyticsServiceRecordWeightData = {
    body: BodyAnalyticsServiceRecordWeight;
    path?: never;
    query?: never;
    url: '/api/analytics_service/record_weight';
};

export type AnalyticsServiceRecordWeightErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyticsServiceRecordWeightError = AnalyticsServiceRecordWeightErrors[keyof AnalyticsServiceRecordWeightErrors];

export type AnalyticsServiceRecordWeightResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AnalyticsServiceRecordWeightResponse = AnalyticsServiceRecordWeightResponses[keyof AnalyticsServiceRecordWeightResponses];

export type AnalyticsServiceGetWeightHistoryData = {
    body: BodyAnalyticsServiceGetWeightHistory;
    path?: never;
    query?: never;
    url: '/api/analytics_service/get_weight_history';
};

export type AnalyticsServiceGetWeightHistoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyticsServiceGetWeightHistoryError = AnalyticsServiceGetWeightHistoryErrors[keyof AnalyticsServiceGetWeightHistoryErrors];

export type AnalyticsServiceGetWeightHistoryResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type AnalyticsServiceGetWeightHistoryResponse = AnalyticsServiceGetWeightHistoryResponses[keyof AnalyticsServiceGetWeightHistoryResponses];

export type AnalyticsServiceSubmitFeedbackData = {
    body: BodyAnalyticsServiceSubmitFeedback;
    path?: never;
    query?: never;
    url: '/api/analytics_service/submit_feedback';
};

export type AnalyticsServiceSubmitFeedbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyticsServiceSubmitFeedbackError = AnalyticsServiceSubmitFeedbackErrors[keyof AnalyticsServiceSubmitFeedbackErrors];

export type AnalyticsServiceSubmitFeedbackResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AnalyticsServiceSubmitFeedbackResponse = AnalyticsServiceSubmitFeedbackResponses[keyof AnalyticsServiceSubmitFeedbackResponses];

export type AnalyticsServiceGetUserProgressReportData = {
    body: BodyAnalyticsServiceGetUserProgressReport;
    path?: never;
    query?: never;
    url: '/api/analytics_service/get_user_progress_report';
};

export type AnalyticsServiceGetUserProgressReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyticsServiceGetUserProgressReportError = AnalyticsServiceGetUserProgressReportErrors[keyof AnalyticsServiceGetUserProgressReportErrors];

export type AnalyticsServiceGetUserProgressReportResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AnalyticsServiceGetUserProgressReportResponse = AnalyticsServiceGetUserProgressReportResponses[keyof AnalyticsServiceGetUserProgressReportResponses];

export type AnalyticsServiceGetTestimonialsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/analytics_service/get_testimonials';
};

export type AnalyticsServiceGetTestimonialsResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type AnalyticsServiceGetTestimonialsResponse = AnalyticsServiceGetTestimonialsResponses[keyof AnalyticsServiceGetTestimonialsResponses];

export type GeneticServiceCreateGeneticTestData = {
    body: BodyGeneticServiceCreateGeneticTest;
    path?: never;
    query?: never;
    url: '/api/genetic_service/create_genetic_test';
};

export type GeneticServiceCreateGeneticTestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GeneticServiceCreateGeneticTestError = GeneticServiceCreateGeneticTestErrors[keyof GeneticServiceCreateGeneticTestErrors];

export type GeneticServiceCreateGeneticTestResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GeneticServiceCreateGeneticTestResponse = GeneticServiceCreateGeneticTestResponses[keyof GeneticServiceCreateGeneticTestResponses];

export type GeneticServiceGetSampleReportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/genetic_service/get_sample_report';
};

export type GeneticServiceGetSampleReportResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GeneticServiceGetSampleReportResponse = GeneticServiceGetSampleReportResponses[keyof GeneticServiceGetSampleReportResponses];

export type GeneticServiceGetUserGeneticTestData = {
    body: BodyGeneticServiceGetUserGeneticTest;
    path?: never;
    query?: never;
    url: '/api/genetic_service/get_user_genetic_test';
};

export type GeneticServiceGetUserGeneticTestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GeneticServiceGetUserGeneticTestError = GeneticServiceGetUserGeneticTestErrors[keyof GeneticServiceGetUserGeneticTestErrors];

export type GeneticServiceGetUserGeneticTestResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    } | null;
};

export type GeneticServiceGetUserGeneticTestResponse = GeneticServiceGetUserGeneticTestResponses[keyof GeneticServiceGetUserGeneticTestResponses];

export type GeneticServiceGetAllSupplementsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/genetic_service/get_all_supplements';
};

export type GeneticServiceGetAllSupplementsResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GeneticServiceGetAllSupplementsResponse = GeneticServiceGetAllSupplementsResponses[keyof GeneticServiceGetAllSupplementsResponses];

export type GeneticServiceGetUserRecommendationsData = {
    body: BodyGeneticServiceGetUserRecommendations;
    path?: never;
    query?: never;
    url: '/api/genetic_service/get_user_recommendations';
};

export type GeneticServiceGetUserRecommendationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GeneticServiceGetUserRecommendationsError = GeneticServiceGetUserRecommendationsErrors[keyof GeneticServiceGetUserRecommendationsErrors];

export type GeneticServiceGetUserRecommendationsResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    } | null;
};

export type GeneticServiceGetUserRecommendationsResponse = GeneticServiceGetUserRecommendationsResponses[keyof GeneticServiceGetUserRecommendationsResponses];

export type SubscriptionServiceCreateSubscriptionData = {
    body: BodySubscriptionServiceCreateSubscription;
    path?: never;
    query?: never;
    url: '/api/subscription_service/create_subscription';
};

export type SubscriptionServiceCreateSubscriptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscriptionServiceCreateSubscriptionError = SubscriptionServiceCreateSubscriptionErrors[keyof SubscriptionServiceCreateSubscriptionErrors];

export type SubscriptionServiceCreateSubscriptionResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SubscriptionServiceCreateSubscriptionResponse = SubscriptionServiceCreateSubscriptionResponses[keyof SubscriptionServiceCreateSubscriptionResponses];

export type SubscriptionServiceGetUserSubscriptionData = {
    body: BodySubscriptionServiceGetUserSubscription;
    path?: never;
    query?: never;
    url: '/api/subscription_service/get_user_subscription';
};

export type SubscriptionServiceGetUserSubscriptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscriptionServiceGetUserSubscriptionError = SubscriptionServiceGetUserSubscriptionErrors[keyof SubscriptionServiceGetUserSubscriptionErrors];

export type SubscriptionServiceGetUserSubscriptionResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    } | null;
};

export type SubscriptionServiceGetUserSubscriptionResponse = SubscriptionServiceGetUserSubscriptionResponses[keyof SubscriptionServiceGetUserSubscriptionResponses];

export type SubscriptionServiceUpdateSubscriptionStatusData = {
    body: BodySubscriptionServiceUpdateSubscriptionStatus;
    path?: never;
    query?: never;
    url: '/api/subscription_service/update_subscription_status';
};

export type SubscriptionServiceUpdateSubscriptionStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscriptionServiceUpdateSubscriptionStatusError = SubscriptionServiceUpdateSubscriptionStatusErrors[keyof SubscriptionServiceUpdateSubscriptionStatusErrors];

export type SubscriptionServiceUpdateSubscriptionStatusResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SubscriptionServiceUpdateSubscriptionStatusResponse = SubscriptionServiceUpdateSubscriptionStatusResponses[keyof SubscriptionServiceUpdateSubscriptionStatusResponses];

export type SubscriptionServiceCreateDeliveryData = {
    body: BodySubscriptionServiceCreateDelivery;
    path?: never;
    query?: never;
    url: '/api/subscription_service/create_delivery';
};

export type SubscriptionServiceCreateDeliveryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscriptionServiceCreateDeliveryError = SubscriptionServiceCreateDeliveryErrors[keyof SubscriptionServiceCreateDeliveryErrors];

export type SubscriptionServiceCreateDeliveryResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SubscriptionServiceCreateDeliveryResponse = SubscriptionServiceCreateDeliveryResponses[keyof SubscriptionServiceCreateDeliveryResponses];

export type SubscriptionServiceGetUserDeliveriesData = {
    body: BodySubscriptionServiceGetUserDeliveries;
    path?: never;
    query?: never;
    url: '/api/subscription_service/get_user_deliveries';
};

export type SubscriptionServiceGetUserDeliveriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscriptionServiceGetUserDeliveriesError = SubscriptionServiceGetUserDeliveriesErrors[keyof SubscriptionServiceGetUserDeliveriesErrors];

export type SubscriptionServiceGetUserDeliveriesResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type SubscriptionServiceGetUserDeliveriesResponse = SubscriptionServiceGetUserDeliveriesResponses[keyof SubscriptionServiceGetUserDeliveriesResponses];

export type SubscriptionServiceGetPricingInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/subscription_service/get_pricing_info';
};

export type SubscriptionServiceGetPricingInfoResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SubscriptionServiceGetPricingInfoResponse = SubscriptionServiceGetPricingInfoResponses[keyof SubscriptionServiceGetPricingInfoResponses];